Algoritmo "TabuadaComWhile"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Marcos Monteiro
// Descrição   : imprime a tabuada de um número digitado.
// Autor   : Mateus Figueredo
// Data atual  : 11/06/2022
Var
numero:inteiro
i:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

   escreva("Digite um número: ")
   leia(numero)

   i<-1
   enquanto i<=10 faca
   escreval(numero," x ",i," = ",numero * i)
   i<-i+1
   fimenquanto
Fimalgoritmo